replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/gcp-devops-project-498805/myapp-repo/myapp
  pullPolicy: IfNotPresent
  tag: "1.0.0"

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

ingress:
  enabled: false

httpRoute:
  enabled: false

resources:
  requests:
    memory: "32Mi"
    cpu: "100m"
  limits:
    memory: "64Mi"
    cpu: "200m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

env:
  APP_ENV: production
  LOG_LEVEL: info
